### ISSUE TITLE
Foutje in hoofdstuk bevolking

### ISSUE THREAD

**Issue by veravandestraat** [provinciesincijfers/omgevingsanalyse#10]
De rood omcirkelde 2022 hieronder zou (denk ik) 1990 moeten zijn.
<img width="626" alt="image" src="https://github.com/provinciesincijfers/omgevingsanalyse/assets/61196697/a9c1648f-a75b-4987-830d-edb2f134bcdf">

@GeertBonte kan jij dit aanpassen?

**Comment by GeertBonte** [comment]
Aangepast.
