### ISSUE TITLE
hoofdstuk 1: jaartal officiële statistiek en eigen verwerking

### ISSUE THREAD

**Issue by HildeC** [provinciesincijfers/omgevingsanalyse#8]
In hoofdstuk 1 van de omgevingsanalyse, bij paragraaf 1.1 Totale bevolking, wordt het aantal inwoners volgens de officiële statistieken vermeld, alsook het aantal inwoners volgens onze eigen verwerking van het Rijksregister. 
Momenteel is de officiële statistiek echter al beschikbaar voor 2023, maar de eigen verwerking nog niet.

de tekst suggereert dat we met eigen verwerking meer mensen tellen dan de officiële statistiek, dat klopt niet meer als je 2 jaartallen door elkaar gebruikt.

Geert kan programmeren dat we de , zolang de eigen verwerking er niet is, we de data van het oudere jaar voor de officiële statistiek behouden. 

mijn voorkeur gaat uit naar zelfde jaartal voor beide bevolkingscijfers.
is dat OK?

**Comment by rudymarynissen** [comment]
is oké voor mij

**Comment by karolienbloemen** [comment]
prima voor mij

**Comment by GeertBonte** [comment]
Aangepast.
